services:
  front:
    image: tallerfrontend:1.0
    ports:
      - "8080:8080"
    networks:
      - netApp

  back:
    image: tallerbackend:1.0
    networks:
      netApp:
        ipv4_address: 172.28.0.2

networks:
  netApp:
    driver: bridge
    ipam:
     config:
      - subnet: 172.28.0.0/16
        gateway: 172.28.5.254
      
  

